### PR TITLE
Quick add new event feature

### PR DESCRIPTION
**Pull request by diffmike**
Hello,
I've implemented quick add feature which is really useful in my opinion. Hopefully will be useful for someone else 🙂 

It sends _Quick query for new event_ into selected calendar (one of active)
Screenshot 2019-04-03 at 22 23 16

### CODE REVIEW

**Comment by deanishe** [comment]
Awesome. This was requested in #4, but Google had disabled the URL, and [I didn't read the documentation properly](https://github.com/deanishe/alfred-gcal/issues/4#issuecomment-457906097).

This required requesting additional permissions, right? What do users need to do after updating?

**Comment by diffmike** [comment]
Right, full access to calendars is required for this feature: `https://www.googleapis.com/auth/calendar - read/write access to Calendars`
The easiest way to update is remove account(s) and add it one more time (new permissions will be requested in that case)

**Comment by deanishe** [comment]
What does that mean for existing users? The workflow will stop working until the user logs out and back in again? Just the new Add feature won't work until the user logs out and back in again?

**Comment by diffmike** [comment]
Workflow would works as it worked. Only the difference for current users will be if they try to create new event with current permissions - new event won't be created and exception will be thrown in the Alfred debug panel.

**Comment by deanishe** [comment]
>  if they try to create new event with current permissions - new event won't be created and exception will be thrown in the Alfred debug panel.

Great that it still works as before for existing users, but we also need something useful in Alfred's UI for when someone with read-only tries to use `gnew`.

The feature is guaranteed to fail for every existing user of the workflow. I'm not comfortable adding it unless the workflow handles that situation gracefully. Almost nobody uses the debugger or reads the docs. They just post screenshots of Alfred doing something that isn't what they were expecting it to do.

What do you think of a [`ReadWrite bool` field on `Account`](https://github.com/deanishe/alfred-gcal/blob/5c14fe73129e5a0f0dbf933087ecf1d1df32de27/account.go#L28)? If [the OAuth flow set `Account.ReadWrite` to `true` on login](https://github.com/deanishe/alfred-gcal/blob/master/auth.go#L147), then only accounts whose tokens have the new permissions would be marked `ReadWrite`, right?

The workflow could then use the `ReadWrite` field to enable/disable the feature.

**Comment by diffmike** [comment]
This is really good point, thanks. I've updated functionality according your suggestion.

**Comment by Morrocotudo** [comment]
Hi! Absolute noob here.
Is it possible to create an event in a different day than today?
Thx!

**Comment by deanishe** [comment]
Dude, [read the instructions](https://github.com/deanishe/alfred-gcal#add-event-format). You just have to enter the date.

**Comment by Morrocotudo** [comment]
Then i guess it's not working for me :/ if i type "test event tomorrow 23:00" it just creates an event today at 23:00 called "Test event tomorrow". Maybe it is a language cnfiguration issue?

**Comment by deanishe** [comment]
> Maybe it is a language cnfiguration issue?

This *appears* to be the case. I tried adding an event to a Google account that's set to German, and it understands neither "tomorrow" nor "morgen" (German for "tomorrow").

There's nothing I can do about it, I'm afraid. The workflow simply passes your query to the Google "QuickAdd" API. There is no option to specify a language, and the input format is undocumented.

You will have to ask Google why it doesn't work.

**Comment by Morrocotudo** [comment]
Ok, I see. Thanks a lot for your help!

**Pull request merged**
